apiVersion: v1
kind: Pod
metadata:
  name: hellok8s-pod
  labels:
    name: hellok8s-pod
spec:
  containers:
  - name: hellok8s
    image: augg1e/hellok8s:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
