apiVersion: v1
kind: Pod
metadata:
  name: hellok8s-pod
  labels:
    name: hellok8s-pod
spec:
  containers:
  - name: hellok8s-container
    image: augg1e/hellok8s:v4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
    env:
      - name: DB_URL
        valueFrom:
          configMapKeyRef:
            name: hellok8s-config
            key: DB_URL